### ISSUE TITLE
BFC

### ISSUE THREAD

**Issue by zhangyachen** [zhangyachen/zhangyachen.github.io#36]
> 浮动，绝对定位元素，inline-blocks, table-cells, table-captions,和overflow的值不为visible的元素，（除了这个值已经被传到了视口的时候）将创建一个新的块级格式化上下文。

会产生BFC的元素：
- 根元素（个人理解是html元素）
- float属性不为none
- position为absolute或fixed
- display为inline-block, table-cell, table-caption, flex, inline-flex
- overflow不为visible

BFC特性：
- 内部的Box会在垂直方向，从顶部开始一个接一个地放置。
- Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生叠加
- 每个元素的margin box的左边， 与包含块border box的左边相接触(对于从左往右的格式化，否则相反)。即使存在浮动也是如此。
- BFC的区域不会与float box叠加。
- BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素，反之亦然。
- 计算BFC的高度时，浮动元素也参与计算。
### 外边距折叠

HTML:

``` html
<p></p>
<p></p>
<p></p>
```

CSS：

``` css
p {
        background: red;
        width: 200px;
        height:200px
}
```

效果：
![image](http://ww3.sinaimg.cn/mw690/701edf03jw1f4edu5xkvcj206c0cowec.jpg)
几个p元素都属于同一个BFC(html元素)，所以发生了外边距折叠的现象。为了防止此现象，我们可以使他们不属于同一个BFC。

HTML:

``` html
<div id="bfc">
    <p></p>
</div>
<p></p>
<p></p>
```

CSS：

``` css
#bfc{
        overflow:hidden;
}
p {
        background: red;
        width: 200px;
        height:200px
}
```

![image](http://ww3.sinaimg.cn/mw690/701edf03jw1f4eh3mig75j206n0brdfn.jpg)
### 防止文字环绕

HTML:

``` HTML
<div class="aside"></div>
<div class="main"></div>
```

CSS:

``` CSS
.aside {
        width: 100px;
        height: 150px;
        float: left;
        background: blue;

}

 .main {
        height: 200px;
        background: #f00;
}
```

效果：
![image](http://ww3.sinaimg.cn/mw690/701edf03jw1f4ek5xnpraj20qj05rdfy.jpg)

> In a block formatting context, each box’s left outer edge touches the left edge of the containing block (for right-to-left formatting, right edges touch). This is true even in the presence of floats (although a box’s line boxes may shrink due to the floats), unless the box establishes a new block formatting context (in which case the box itself may become narrower due to the floats).

在BFC中，每一个盒子的左外边距会触碰到包含块的左边框。在有浮动元素的情况下也是如此（即使是盒子的文本内容由于浮动元素而被压缩）。如果不想有如上的效果，盒子需要建立一个新的BFC（此时盒子会因为浮动元素的存在而变窄）。

HTML不变。

``` CSS
.aside {
        width: 100px;
        height: 150px;
        float: left;
        background: blue;

}

 .main {
        height: 200px;
        background: #f00;
        overflow:hidden;
}
```

![image](https://cloud.githubusercontent.com/assets/14103319/15665631/d2b0d8b0-273e-11e6-8406-1d05564407cf.png)
### 包含浮动元素

HTML:

``` html
<div class="BFC">
    <div class="box"></div>
    <div class="box"></div>
</div>
```

CSS:

``` css
.BFC {
        border: 5px solid #f00;
        width: 300px;
    }

.box {
        border: 5px solid blue;
        width:100px;
        height: 100px;
        float: left;
    }
```

![image](https://cloud.githubusercontent.com/assets/14103319/15666121/8e35067c-2741-11e6-9c74-834890350113.png)
根据：计算BFC的高度时，浮动元素也参与计算。我们让父元素建立一个BFC，包含浮动元素的高度。（以前一直不懂，现在明白了）

HTML不变。
CSS：

``` CSS
.BFC {
        border: 5px solid #f00;
        width: 300px;
        overflow:hidden;
    }

    .box {
        border: 5px solid blue;
        width:100px;
        height: 100px;
        float: left;
    }
```

![image](https://cloud.githubusercontent.com/assets/14103319/15666211/1d5c96da-2742-11e6-8741-e6402a8344ff.png)

参考资料：http://www.w3cplus.com/css/understanding-bfc-and-margin-collapse.html
https://www.sitepoint.com/understanding-block-formatting-contexts-in-css/
http://www.html-js.com/article/1866
